name: taalk
description: A new Flutter application for chatting

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Get Location
  http: ^0.12.0+4
  location: ^2.3.5
  geocoder: ^0.2.1
  json_annotation: ^3.0.1
  #Local Storage
  shared_preferences: ^0.5.6+1
  #Popup
  progress_dialog: ^1.2.0
  #Date
  intl: ^0.16.1
  #Device Informations
  imei_plugin: ^1.1.6
  #SlidingUp/BottomSheet
  sliding_up_panel: ^1.0.0
  #Page Indicator Slider
  page_indicator: ^0.3.0
  #Access/Create Storage
  path_provider: ^1.6.0
  dio: ^3.0.8
  #Share File
  share_extend: ^1.1.1
  #Permissions
  #simple_permissions: ^0.1.9
  #Cache Manager
  flutter_cache_manager: ^1.1.3
  #Save File
#  gallery_saver: ^1.0.7
  image_gallery_saver: ^1.2.2
#  pinch_zoom_image: ^0.2.5
  #Toast
  fluttertoast: ^3.1.3
  #Animation
  fade: ^1.0.0
  #Firebase
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.1.5+1
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.1
  firebase_auth: ^0.15.4
  firebase_storage: ^3.1.1
  #Image Picker
#  image_picker_saver: ^0.3.0
  image_picker: ^0.6.1+4
  photo_view: ^0.9.2
  cached_network_image: ^2.0.0
  gallery_saver: ^1.0.7
  #Color Picker
  flutter_colorpicker: ^0.2.6
  #Button
  unicorndial: ^1.1.5
  #Animation Layout
  flutter_staggered_animations: ^0.1.2
  responsive_widgets: ^1.0.2
  #Link
  flutter_linkify: ^2.1.0
  url_launcher:
  #Carousal/Image Slide
  carousel_slider: ^1.4.1
  intervalprogressbar: ^1.0.1
  move_to_background: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/ic_active.png
    - assets/images/ic_inactive.png
    - assets/images/ic_absent.png
    - assets/images/ic_background_green_64px.png
    - assets/images/ic_edit_green_64px.png
    - assets/images/ic_employee_list.png
    - assets/images/ic_inactive.png
    - assets/images/ic_launcher_shuba.png
    - assets/images/ic_leave.png
    - assets/images/ic_leave_two.png
    - assets/images/ic_messages.png
    - assets/images/ic_monitoring.png
    - assets/images/ic_panic.png
    - assets/images/ic_safe.png
    - assets/images/ic_recycle_green_24px.png
    - assets/images/ic_sales.png
    - assets/images/ic_server_green_24px.png
    - assets/images/ic_set_api_green_24px.png
    - assets/images/ic_settings.png
    - assets/images/ic_work_white.png
    - assets/images/ic_house_white.png
    - assets/images/ic_clockin.png
    - assets/images/ic_clockout.png
    - assets/images/ic_shuba.png
    - assets/images/ic_bell_64px.png
    - assets/images/ic_theme_green_64px.png
    - assets/images/ic_panic_press.png
    - assets/images/ic_btn_panic.png
    - assets/images/ic_edit_profile.png
    - assets/images/ic_user_karir.jpg
    - assets/images/oops.png
    - assets/images/ic_user_example.png
    - assets/images/ic_gallery_attach.png
    - assets/images/ic_camera_attach.png
    - assets/images/logo_icon_shuba.png
    - assets/images/ic_map_attach.png
    - assets/images/ic_forward_chat.png
    - assets/images/ic_copy_chat.png
    - assets/images/ic_employee.png
    - assets/images/ic_calender_attendance.png
    - assets/images/ic_conferences.png
    - assets/images/ic_discuss.png
    - assets/images/ic_list_panic.png
    - assets/images/ic_download.png
    - assets/images/ic_image_detail.png
    - assets/images/ic_create_group.png
    - assets/images/ic_form_create_group.png
    - assets/images/ic_profile_group.png
    - assets/images/ic_create_story.png
    - assets/images/folder.png
    - assets/images/ic_fingerprint_red.png
    - assets/images/ic_fingerprint_green.png
    - assets/images/ic_launcher_shuba_notitle.png
    - assets/images/ic_broadcast.png
    - assets/images/ic_discuss_chat.png
    - assets/images/ic_discuss_chat_black.png
    - assets/images/ic_discuss_group.png
    - assets/images/ic_discuss_group_black.png
    - assets/images/ic_discuss_story.png
    - assets/images/ic_discuss_story_black.png
    - assets/images/ic_header_drawer.png
    - assets/images/create_group_image.png
    - assets/images/ic_tab_chats.png
    - assets/images/ic_tab_group.png
    - assets/images/ic_tab_stories.png
    - assets/images/ic_launcher_notitle.png
    - assets/images/ic_like_green.png
    - assets/images/ic_dislike_red.png
    - assets/images/ic_notif_add_group.png
    - assets/images/ic_notif_delete_group.png
    - assets/images/ic_notif_story.png
    - assets/images/timeline_image.jpg
    - assets/images/img_work.jpg
    - assets/images/img_discuss.jpg
    - assets/images/img_ilustration_discuss.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
